### ISSUE TITLE
[Symbol.dispose]() is placed after all other methods

### ISSUE THREAD

**Issue by hugosvirak** [seiyab/prettier-plugin-sort-members#66]
Great project so far! It would be great if I could keep my `[Symbol.dispose]() {}` function to be just after the constructor. I can't quite figure it out, currently it goes to the bottom of the methods, please let me know if it's possible to keep it close to the constructor.

This dispose mechanism is a new feature, see more here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html.

**Comment by seiyab** [comment]
Thank you for reporting it! I guess that you are using sortMembersAlphabetically. typescript-eslint with `"order": "alphabetically"` puts such method before any other methods. I consider this incompatibility is a bug in prettier-plugin-sort-members. I'll fix it.
[TypeScript ESLint Playground](https://typescript-eslint.io/play/#ts=5.3.0-beta&showAST=es&fileType=.tsx&code=FAYwNghgzlAEBKBTKB7ArgJxI2BvYssIKAdlAC4ZojkoYAUAlLgL7AGwcC2i5AFigAmTPLDYcA2gGUAnlwBGKMADpBASygAHFFEQBdEfg7iWQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0YANqQ%2B0IZAA0mSKIBmAQwT4pwSENHQpkTfGIALTb3yUyZ%2BIUgBfZwF1wYZyGdA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

By the way, you want to keep constructor and `[Symbol.dispose](){}` together since both relate to lifecycle of class instances, I suppose. Just improving compatibility with typescript-eslint's default won't completely achieve it. For example, getters and setters will go to between constructor and any method including `[Symbol.dispose](){}`. Technically we can keep `[Symbol.dispose](){}` to be just after the constructor implementing an option as a new feature. However, I don't want to increase the number of options. Does just fixing a bug described above will resolve your issue practially? In other words, do you use getters or setters?
[TypeScript ESLint Playground](https://typescript-eslint.io/play/#ts=5.3.0-beta&showAST=es&fileType=.tsx&code=FAYwNghgzlAEBKBTKB7ArgJxI2BvYssIKAdlAC4ZojkoYAUAlHrAL7AGwDaAygJ4BbAEYowAOgAmASygAHFFEQBdJng6F2nAOaJysWRhSzVuDLswlYABk2sgA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEKQAIBcBPABxQGNoBLY-AWhXkoDt8B6AW0XYCNFpaA9tAAmfZgHN0YANqQ%2B0IZAA0mSKIBmAQwT4pwSENHQpkTfGIALTb3yUyZ%2BIUgBfZwF1wYZyGdA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)

**Comment by hugosvirak** [comment]
@seiyab Thank you very much for your quick response and pull request. Yes I wanted to keep them together because they are related to the life cycle. I don't currently use getters and setters, although yes the issue the issue would arise in that case. My issue is resolved in v0.2.2, therefore I'll close this.

Note to others: reload VS Code after updating this library!
